"""Phase 5: Docker Build & Summary Report."""

from __future__ import annotations

import subprocess
import textwrap
import time
from pathlib import Path

from ..constants import (
    A2A_PORT,
    DOCKER_BUILD_TIMEOUT,
    DOCKER_IMAGE_NAME,
    DOCKER_IMAGE_TAG,
)
from ..models import PipelineState


def run_build_push(
    state: PipelineState,
    image_tag: str = DOCKER_IMAGE_TAG,
) -> PipelineState:
    """Execute docker build and produce summary report.

    Steps:
    1. Generate .dockerignore (if not present)
    2. Run docker build
    3. Inspect image size
    """
    project_root = state.project_root

    # ── Step 0: Generate .dockerignore ─────────────────────────────
    _generate_dockerignore(project_root)

    # ── Step 1: Docker Build ─────────────────────────────────────────
    full_tag = f"{DOCKER_IMAGE_NAME}:{image_tag}"
    containerisation_dir = project_root / "beagle_containerisation"

    t0 = time.monotonic()
    ok, build_output = _docker_build(project_root, containerisation_dir, full_tag)
    elapsed = time.monotonic() - t0

    if not ok:
        state.errors.append(f"Phase 5: Docker build failed:\n{build_output}")
        state.phase5_passed = False
        return state

    state.build_duration_seconds = elapsed

    # ── Step 2: Inspect Image ────────────────────────────────────────
    size_mb = _get_image_size_mb(full_tag)
    image_id = _get_image_id(full_tag)

    state.image_id = image_id
    state.image_size_mb = size_mb
    state.phase5_passed = True
    state.phase_details["phase5_detail"] = f"{full_tag} — {size_mb:.0f}MB — built in {elapsed:.1f}s"

    return state


def _docker_build(
    project_root: Path,
    containerisation_dir: Path,
    full_tag: str,
) -> tuple[bool, str]:
    """Execute docker build -t <tag> -f <Dockerfile> ."""
    dockerfile_path = containerisation_dir / "Dockerfile"
    cmd = [
        "docker",
        "build",
        "-f",
        str(dockerfile_path),
        "-t",
        full_tag,
        ".",
    ]

    try:
        result = subprocess.run(
            cmd,
            cwd=project_root,
            capture_output=True,
            text=True,
            timeout=DOCKER_BUILD_TIMEOUT,
        )
        if result.returncode == 0:
            return True, result.stdout.strip()
        return False, result.stderr[-1000:]
    except FileNotFoundError:
        return False, "docker not found — is Docker installed?"
    except subprocess.TimeoutExpired:
        return False, "Docker build timed out after 600s"


def _get_image_size_mb(full_tag: str) -> float:
    """Get image size in MB via docker inspect."""
    try:
        result = subprocess.run(
            ["docker", "inspect", "--format", "{{.Size}}", full_tag],
            capture_output=True,
            text=True,
            timeout=30,
        )
        if result.returncode == 0:
            size_bytes = int(result.stdout.strip())
            return round(size_bytes / (1024 * 1024), 1)
    except (OSError, ValueError, subprocess.TimeoutExpired):
        pass
    return 0.0


def _get_image_id(full_tag: str) -> str:
    """Get image ID via docker inspect."""
    try:
        result = subprocess.run(
            ["docker", "inspect", "--format", "{{.Id}}", full_tag],
            capture_output=True,
            text=True,
            timeout=30,
        )
        if result.returncode == 0:
            return result.stdout.strip()[:19]
    except (OSError, subprocess.TimeoutExpired):
        pass
    return "unknown"


def _generate_dockerignore(project_root: Path) -> None:
    """Generate .dockerignore to minimize Docker context."""
    dockerignore_path = project_root / ".dockerignore"
    content = textwrap.dedent("""\
        # ═══════════════════════════════════════════════════════════
        # Beagle Factory — Docker Build Context Exclusions
        # Auto-generated by beagle-dockeriser
        # ═══════════════════════════════════════════════════════════

        # Version control
        .git/
        .gitignore

        # Python bytecode and caches
        __pycache__/
        *.py[cod]
        *$py.class
        *.so

        # Virtual environments
        .venv/
        venv/
        env/
        /opt/

        # IDE / Editor files
        .idea/
        .vscode/
        *.swp
        *.swo
        *~

        # Testing and coverage
        .pytest_cache/
        htmlcov/
        .coverage
        coverage.xml

        # Lint caches
        .ruff_cache/
        .mypy_cache/

        # Build artifacts (NOT dist/ — we NEED the wheel!)
        build/
        *.egg-info/

        # Documentation
        docs/
        docs_to_index/
        docs_to_index_code/
        *.md
        !README.md

        # Development scripts and plans
        scripts/
        plans/
        .beagle/

        # Test data and benchmarks
        benchmarks/
        tests/

        # OS files
        .DS_Store
        Thumbs.db

        # Beagle runtime data (not for Docker context)
        data/

        # Config overrides (container uses defaults + env vars)
        .config/

        # Containers and deployment tooling
        beagle_containerisation/

        # Reports and logs
        reports/
        *.log
    """)
    dockerignore_path.write_text(content)


def print_summary(state: PipelineState, full_tag: str) -> None:
    """Print the deployment summary and 'How to Start' guide."""
    print()
    print("=" * 62)
    print("  Beagle Docker Build — Summary")
    print("=" * 62)
    print(f"  Image:        {full_tag}")
    print(f"  Image ID:     {state.image_id}")
    print(f"  Image Size:   {state.image_size_mb:.0f} MB")
    print(f"  Build Time:   {state.build_duration_seconds:.1f}s")
    if state.wheel_spec:
        print(f"  Wheel:        {state.wheel_spec.name}")
        print(f"  Wheel Size:   {state.wheel_spec.size_mb} MB")
    if state.dockerfile_path:
        print(f"  Dockerfile:   {state.dockerfile_path}")
    if state.compose_path:
        print(f"  Compose:      {state.compose_path}")
    print("=" * 62)
    print()
    print("  How to Start:")
    print(f"    cd {state.project_root}")
    print("    cp .env.example .env          # customize if needed")
    print("    docker compose -f beagle_containerisation/docker-compose.yaml up -d")
    print("    docker compose -f beagle_containerisation/docker-compose.yaml ps")
    print("    docker compose -f beagle_containerisation/docker-compose.yaml logs -f")
    print(f"    curl http://127.0.0.1:{A2A_PORT}/health")
    print("    docker compose -f beagle_containerisation/docker-compose.yaml down")
    print()
