"""Phase 4: Docker Compose Generator — OptiPlex persistence configuration."""

from __future__ import annotations

import textwrap
from pathlib import Path

from ..constants import (
    A2A_BIND_ADDRESS,
    A2A_PORT,
    CONTAINER_CHECKPOINTS_DIR,
    CONTAINER_RAG_DIR,
    CONTAINER_SECRETS_FILE,
    DOCKER_IMAGE_NAME,
    DOCKER_IMAGE_TAG,
    HOST_CHECKPOINTS_DIR,
    HOST_RAG_DIR,
    HOST_SECRETS_FILE,
)
from ..models import ComposeSpec, PipelineState, VolumeSpec


def run_compose_gen(state: PipelineState) -> PipelineState:
    """Generate the docker-compose.yaml for OptiPlex deployment.

    Writes docker-compose.yaml to the containerisation directory.
    Also creates .env template if not present.
    Creates ./data/ directories if not present.
    """
    spec = ComposeSpec(
        image_name=DOCKER_IMAGE_NAME,
        image_tag=DOCKER_IMAGE_TAG,
        container_name="beagle-factory",
        restart_policy="unless-stopped",
        volumes=[
            VolumeSpec(HOST_RAG_DIR, CONTAINER_RAG_DIR),
            VolumeSpec(HOST_CHECKPOINTS_DIR, CONTAINER_CHECKPOINTS_DIR),
            VolumeSpec(HOST_SECRETS_FILE, CONTAINER_SECRETS_FILE, read_only=True),
        ],
        ports=[f"{A2A_BIND_ADDRESS}:{A2A_PORT}:{A2A_PORT}"],
        env_file=".env",
    )

    compose_content = render_compose_yaml(spec)

    containerisation_dir = state.project_root / "beagle_containerisation"
    containerisation_dir.mkdir(parents=True, exist_ok=True)
    compose_path = containerisation_dir / "docker-compose.yaml"
    compose_path.write_text(compose_content)

    _ensure_data_dirs(state.project_root)
    _create_env_template(state.project_root)

    state.compose_path = compose_path
    state.compose_spec = spec
    state.phase4_passed = True
    state.phase_details["phase4_detail"] = f"Written to {compose_path}"

    return state


def render_compose_yaml(spec: ComposeSpec) -> str:
    """Render a ComposeSpec into a docker-compose.yaml string."""

    lines = []
    lines.append("# ═══════════════════════════════════════════════════════════")
    lines.append("# Beagle Factory — Docker Compose Configuration")
    lines.append("# Auto-generated by beagle-dockeriser")
    lines.append("# Target: MSI MPG Z390I GAMING EDGE AC (Intel i7-9700K) (single-host)")
    lines.append("# DO NOT EDIT — changes will be overwritten on next deployment")
    lines.append("# ═══════════════════════════════════════════════════════════")
    lines.append("")
    lines.append("services:")
    lines.append(f"  {spec.container_name}:")
    lines.append(f"    image: {spec.image_name}:{spec.image_tag}")
    lines.append(f"    container_name: {spec.container_name}")
    lines.append(f"    restart: {spec.restart_policy}")
    lines.append("    ports:")
    if spec.ports:
        lines.append(f'      - "{spec.ports[0]}"')
    lines.append("    volumes:")
    for v in spec.volumes:
        rw = ":ro" if v.read_only else ""
        lines.append(f"      - {v.host_path}:{v.container_path}{rw}")
    lines.append("    environment:")
    lines.append("      - BEAGLE_EXECUTION_ENV=docker")
    lines.append("      # Explicitly unset DOCKER_HOST to prevent container from")
    lines.append("      # inheriting the host's Orpheus-proxied socket path.")
    lines.append("      - DOCKER_HOST=")
    lines.append("      - BEAGLE_LOG_LEVEL=${BEAGLE_LOG_LEVEL:-INFO}")
    lines.append("      - BEAGLE_BUDGET_USD=${BEAGLE_BUDGET_USD:-10.0}")
    lines.append("      - GOOSE_PROVIDER=${GOOSE_PROVIDER:-ollama_cloud}")
    lines.append("      - GOOSE_MODEL=${GOOSE_MODEL:-glm-5}")
    lines.append("    env_file:")
    lines.append(f"      - {spec.env_file}")
    lines.append("    healthcheck:")
    lines.append("      test:")
    lines.append("        - CMD")
    lines.append("        - python")
    lines.append("        - -c")
    lines.append("        - \"import beagle; print('ok')\"")
    lines.append("      interval: 30s")
    lines.append("      timeout: 10s")
    lines.append("      retries: 3")
    lines.append("    stdin_open: false")
    lines.append("    tty: false")
    lines.append("    logging:")
    lines.append("      driver: json-file")
    lines.append("      options:")
    lines.append('        max-size: "10m"')
    lines.append('        max-file: "3"')
    lines.append("")

    return "\n".join(lines)


def _ensure_data_dirs(project_root: Path) -> None:
    """Create data persistence directories on host if they don't exist."""
    for d in [
        project_root / "data" / "rag",
        project_root / "data" / "checkpoints",
    ]:
        d.mkdir(parents=True, exist_ok=True)


def _create_env_template(project_root: Path) -> None:
    """Create .env template file if it doesn't already exist."""
    env_path = project_root / ".env"
    if env_path.exists():
        return

    template = textwrap.dedent("""\
        # Beagle Factory Environment Variables
        # Customize for your deployment

        # Model provider (ollama_cloud, openai, anthropic, etc.)
        GOOSE_PROVIDER=ollama_cloud
        GOOSE_MODEL=glm-5

        # Budget cap (USD per workflow run)
        BEAGLE_BUDGET_USD=10.0

        # Logging
        BEAGLE_LOG_LEVEL=INFO
    """)
    env_path.write_text(template)
