"""Phase 3: Dockerfile Generator — produces hardened multi-stage Dockerfile."""

from __future__ import annotations

from ..constants import (
    A2A_PORT,
    CONTAINER_APP_DIR,
    CONTAINER_DATA_DIR,
    CONTAINER_GID,
    CONTAINER_HOME,
    CONTAINER_UID,
    CONTAINER_USER,
    DOCKERFILE_ENV,
    ENTRYPOINT_CMD,
    HEALTHCHECK_INTERVAL,
    HEALTHCHECK_RETRIES,
    HEALTHCHECK_TIMEOUT,
    PROJECT_VERSION,
    PYTHON_DOCKER_IMAGE,
    STOP_SIGNAL,
)
from ..models import DockerfileSpec, PipelineState
from .build import run_build


def run_dockerfile_gen(state: PipelineState) -> PipelineState:
    """Generate the production Dockerfile.

    Reads wheel spec from Phase 2 output.
    If no wheel exists yet, runs Phase 2 first.
    Writes Dockerfile to containerisation dir.
    """
    if not state.wheel_spec:
        state = run_build(state)
        if not state.phase2_passed:
            state.errors.append("Phase 3: Cannot proceed — wheel build failed")
            state.phase3_passed = False
            return state

    wheel_spec = state.wheel_spec
    assert wheel_spec is not None

    spec = DockerfileSpec(
        base_image=PYTHON_DOCKER_IMAGE,
        container_user=CONTAINER_USER,
        container_uid=CONTAINER_UID,
        container_gid=CONTAINER_GID,
        container_home=CONTAINER_HOME,
        app_dir=CONTAINER_APP_DIR,
        data_dir=CONTAINER_DATA_DIR,
        wheel_filename=wheel_spec.name,
        env_vars=dict(DOCKERFILE_ENV),
        expose_ports=[A2A_PORT],
        stop_signal=STOP_SIGNAL,
        entrypoint=list(ENTRYPOINT_CMD),
        healthcheck_interval=HEALTHCHECK_INTERVAL,
        healthcheck_timeout=HEALTHCHECK_TIMEOUT,
        healthcheck_retries=HEALTHCHECK_RETRIES,
        version=PROJECT_VERSION,
    )

    dockerfile_content = render_dockerfile(spec)

    containerisation_dir = state.project_root / "beagle_containerisation"
    containerisation_dir.mkdir(parents=True, exist_ok=True)
    dockerfile_path = containerisation_dir / "Dockerfile"
    dockerfile_path.write_text(dockerfile_content)

    state.dockerfile_path = dockerfile_path
    state.dockerfile_spec = spec
    state.phase3_passed = True
    state.phase_details["phase3_detail"] = f"Written to {dockerfile_path}"

    return state


def render_dockerfile(spec: DockerfileSpec) -> str:
    """Render a DockerfileSpec into a Dockerfile string."""

    def _env_block(env_vars: dict[str, str]) -> str:
        """Build ENV instruction block."""
        lines = []
        keys = list(env_vars.keys())
        for i, k in enumerate(keys):
            v = env_vars[k]
            if i < len(keys) - 1:
                lines.append(f"    {k}={v} \\")
            else:
                lines.append(f"    {k}={v}")
        return "ENV \\\n" + "\n".join(lines)

    env_block = _env_block(spec.env_vars)
    expose_lines = "\n".join(f"EXPOSE {port}" for port in spec.expose_ports)

    lines = []
    lines.append("# ═══════════════════════════════════════════════════════════")
    lines.append("# Beagle Factory — Multi-Stage Production Docker Image")
    lines.append("# Auto-generated by beagle-dockeriser")
    lines.append(f"# Version: {spec.version}")
    lines.append("# DO NOT EDIT — changes will be overwritten on next deployment")
    lines.append("# ═══════════════════════════════════════════════════════════")
    lines.append("")
    lines.append("# ── Stage 1: Builder ──────────────────────────────────────────")
    lines.append(f"FROM {spec.base_image} AS builder")
    lines.append("")
    lines.append("# Install uv for fast wheel installation")
    lines.append("COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv")
    lines.append("")
    lines.append("# Copy the pre-built wheel from dist/")
    lines.append("COPY dist/ /tmp/dist/")
    lines.append("")
    lines.append("# Pre-install CPU-only torch so the wheel resolution doesn't pull GPU torch.")
    lines.append("# --index-url forces resolution exclusively through the CPU index so that")
    lines.append("# GPU torch from PyPI cannot win resolution.")
    lines.append(
        "RUN uv pip install --system --prefix=/install \\\n"
        "    --index-url https://download.pytorch.org/whl/cpu \\\n"
        "    'torch>=2.6,<3'"
    )
    lines.append("")
    lines.append("# Install the wheel.  torch is already satisfied → resolver will not replace it.")
    lines.append(
        f"RUN uv pip install --system --prefix=/install \\\n"
        f"    /tmp/dist/{spec.wheel_filename} && \\\n"
        f"    rm -rf /tmp/dist"
    )
    lines.append("")
    lines.append("# ── Stage 2: Runner ───────────────────────────────────────────")
    lines.append(f"FROM {spec.base_image} AS runner")
    lines.append("")
    lines.append("# Install system dependencies")
    lines.append("RUN apt-get update && apt-get install -y --no-install-recommends \\")
    lines.append("    ca-certificates curl && \\")
    lines.append("    rm -rf /var/lib/apt/lists/*")
    lines.append("")
    lines.append("# Create non-root user")
    lines.append(f"RUN groupadd --gid {spec.container_gid} {spec.container_user} && \\")
    lines.append(f"    useradd --uid {spec.container_uid} --gid {spec.container_user} \\")
    lines.append(f"    --shell /bin/bash --create-home {spec.container_user}")
    lines.append("")
    lines.append("# Create application directories")
    lines.append(
        f"RUN mkdir -p {spec.data_dir}/rag {spec.app_dir}/state {spec.app_dir}/output && \\"
    )
    lines.append(f"    chown -R {spec.container_user}:{spec.container_user} {spec.app_dir}")
    lines.append("")
    lines.append("# Copy installed packages from builder")
    lines.append("COPY --from=builder /install /usr/local")
    lines.append("")
    lines.append("# Set environment variables")
    lines.append(env_block)
    lines.append("")
    lines.append("# Expose A2A federation port")
    for line in expose_lines.split("\n"):
        lines.append(line)
    lines.append("")
    lines.append("# Graceful shutdown signal")
    lines.append(f"STOPSIGNAL {spec.stop_signal}")
    lines.append("")
    lines.append("# Health check")
    lines.append(f"HEALTHCHECK --interval={spec.healthcheck_interval}s \\")
    lines.append(f"    --timeout={spec.healthcheck_timeout}s \\")
    lines.append(f"    --retries={spec.healthcheck_retries} \\")
    lines.append("    CMD python -c \"import beagle; print('ok')\" || exit 1")
    lines.append("")
    lines.append("# Switch to non-root user")
    lines.append(f"USER {spec.container_user}")
    lines.append("")
    lines.append("# Set working directory")
    lines.append(f"WORKDIR {spec.app_dir}")
    lines.append("")
    lines.append("# Entrypoint: the Beagle CLI")
    lines.append('ENTRYPOINT ["beagle"]')
    lines.append("")

    return "\n".join(lines)
